version: "3.8"

services:

  # --- MQTT broker ---
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mesh_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - /path/to/meshtastic/mqtt/data:/mosquitto/data
      - /path/to/meshtastic/mqtt/log:/mosquitto/log
      - /path/to/meshtastic/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /path/to/meshtastic/mqtt/mosquitto.passwd:/mosquitto/config/passwd

  # --- Meshview itself ---
  meshview:
    image: meshview-docker-image:latest # built outside of compose
    container_name: meshview
    restart: unless-stopped
    ports:
      - "3010:8081"
    volumes:
      - /path/to/meshtastic/meshview/config.ini:/app/config.ini
      - /path/to/meshtastic/meshview/packets.db:/app/packets.db
      # - /path/to/meshtastic/meshview/repo/meshview:/app/meshview/ # needed only for development      
    environment:
      - TZ=${TZ:-UTC} # set this to your timezone